### PR TITLE
Update hazelcast to 4.0.2 and add hazelcast-kubernetes

### PR DESCRIPTION
**Pull request by cristichiru**
Reason: needed this to work in a kubernetes environment, together with Kong and lua-resty-openidc (using lua-session)

### CODE REVIEW

**Comment by gregoire-rolland-cbp** [comment]
Hi,

Thanks a lot for your pull request.

Could you add some little documentation in the readme to explain your needs and how you support them ?

Regards,
Grégoire.

**Comment by cristichiru** [comment]
Hi Gregoire,

The needs were:
1. A Distributed SHM for oidc plugin for kong gateway (based on Nginx), deployed in Kubernetes
2. Containerize this project and deploy it in Kubernetes, as a Hazelcast cluster, not just a single instance
3. Have a newer version of Hazelcast so we can monitor it with existing Management Center (major versions need to be aligned)

I do recommend that you create a Docker hub account (e.g. grrolland), and set up webhooks for this github project. Docker hub will automatically pick up the proposed Dockerfile and build it. If you add also hooks for releases, will create appropriate tags for each github release.

**Comment by grrolland** [comment]
Thanks for your contribution. I merge your request as soon as possible. 
I will follow your advice and create a docker hub account later (I'm out of office now, in holidays).

**Pull request merged**
